class CfgRadio
{
	sounds[] = {};
	class C_FollowConfirm_1
	{
		// display name
		name	= "";
		// filename, volume, pitch
		sound[]	= { "", db - 100, 1.0 };
		// radio caption
		title	= "I'll follow your lead.";
	};
	class C_FollowConfirm_2
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 }; // .wss implied
		title	= "Get me out of here!";
	};
	class C_FollowConfirm_4
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "Lead ahead, I am behind you.";
	};
	class C_FollowConfirm_5
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "Hurry, I don't want to die!";
	};
	class C_FollowConfirm_6
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "Where are we going?";
	};

    class IDAP_FollowOrder_1
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "Follow me!";
	};
    class IDAP_FollowOrder_2
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "Stay behind me!";
	};
    class IDAP_FollowOrder_3
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "Let's get out of here!";
	};
    class IDAP_FollowOrder_4
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "I am here to get you out. Follow my lead!";
	};
    class IDAP_FollowOrder_5
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "I'll take you to my vehcile to get you out of here.";
	};
    class IDAP_FollowOrder_6
	{
		name	= "";
		sound[]	= { "", db - 100, 1.0 };
		title	= "I'll bring you somewhere safe. Stay close!";
	};
};