//https://community.bistudio.com/wiki/Arma_3_Curator#Using_Cost_Tables
params [
    ["_zeuslogic",objNull],
    ["_mode",-1]
];

switch (_mode) do {
    case -1: {

    };
    case 0: {
        //add addon to back of list
        //to get addons
        If (isnil "MIS_unitAddonsList") then {
            MIS_unitAddonsList = [];
        };
        MIS_unitAddonsList pushBackUnique ([cursorObject] call BIS_fnc_unitAddon);
        //monitor if it's already in list
        //[cursorObject] call BIS_fnc_unitAddon in (missionNamespace getvariable ["MIS_unitAddonsList",[]]);
    };
    case 1: {
        //generate Open Office Table
        //all addons required
        _addons = [
            "A3_Air_F_Orange_UAV_01","A3_Structures_F_Orange_Humanitarian_Camps",
            "A3_Supplies_F_Orange_CargoNets","A3_Props_F_Orange_Humanitarian_Supplies",
            "A3_Soft_F_Orange_Truck_02","A3_Soft_F_Orange_Van_02",
            "A3_Soft_F_Orange_Offroad_01","A3_Soft_F_Orange_Offroad_02",
            "A3_Air_F_Orange_Heli_Transport_02","","A3_Soft_F_Orange_UGV_01",
            "A3_Air_F_Orange_UAV_06","A3_Structures_F_Heli_Items_Luggage",
            "A3_Structures_F_Ind_Cargo","A3_Supplies_F_Heli_CargoNets"
        ];
        //generate open office table to clipboard
        [_addons,"ods","IDAP_costaddons",[civilian,sideUnknown]] spawn bis_fnc_exportCuratorCostTable;
    };
    case 2: {
        //Set Values for Zeus
        // Generated by BIS_fnc_exportCuratorCostTable
        // [["A3_Air_F_Orange_UAV_01","A3_Structures_F_Orange_Humanitarian_Camps","A3_Supplies_F_Orange_CargoNets","A3_Props_F_Orange_Humanitarian_Supplies","A3_Soft_F_Orange_Truck_02","A3_Soft_F_Orange_Van_02","A3_Soft_F_Orange_Offroad_01","A3_Soft_F_Orange_Offroad_02","A3_Air_F_Orange_Heli_Transport_02","","A3_Soft_F_Orange_UGV_01","A3_Air_F_Orange_UAV_06","A3_Structures_F_Heli_Items_Luggage","A3_Structures_F_Ind_Cargo","A3_Supplies_F_Heli_CargoNets"],"ods","IDAP_costaddons",[3,4]] call BIS_fnc_exportCuratorCostTable;
        _A3_Air_F_Orange_UAV_01 = ['C_IDAP_UAV_01_F',0.1,'',0];
        _A3_Structures_F_Orange_Humanitarian_Camps = ['Land_MedicalTent_01_floor_dark_F',0.01,'Land_MedicalTent_01_floor_light_F',0.01,'Land_MedicalTent_01_white_IDAP_closed_F',0.01,'Land_MedicalTent_01_white_IDAP_med_closed_F',0.2,'Land_MedicalTent_01_white_IDAP_open_F',0.01,'Land_MedicalTent_01_white_IDAP_outer_F',0.01,'',0];
        _A3_Supplies_F_Orange_CargoNets = ['C_IDAP_CargoNet_01_supplies_F',0.05,'',0];
        _A3_Props_F_Orange_Humanitarian_Supplies = ['Land_PlasticCase_01_large_idap_F',0.05,'Land_PlasticCase_01_medium_idap_F',0.05,'Land_FoodSacks_01_cargo_brown_idap_F',0.05,'Land_FoodSacks_01_cargo_white_idap_F',0.05,'Land_FoodSacks_01_small_brown_idap_F',0.05,'Land_FoodSacks_01_small_white_idap_F',0.05,'Land_PaperBox_01_open_boxes_F',0.05,'Land_PaperBox_01_open_water_F',0.05,'Land_PaperBox_01_small_stacked_F',0.05,'Land_WaterBottle_01_stack_F',0.05,'',0];
        _A3_Soft_F_Orange_Truck_02 = ['C_IDAP_Truck_02_F',0.1,'C_IDAP_Truck_02_transport_F',0.15,'C_IDAP_Truck_02_water_F',0.25,'',0];
        _A3_Soft_F_Orange_Van_02 = ['C_IDAP_Van_02_medevac_F',0.5,'C_IDAP_Van_02_transport_F',0.1,'C_IDAP_Van_02_vehicle_F',0.1,'',0];
        _A3_Soft_F_Orange_Offroad_01 = ['C_IDAP_Offroad_01_F',0.05,'',0];
        _A3_Soft_F_Orange_Offroad_02 = ['C_IDAP_Offroad_02_unarmed_F',0.05,'',0];
        _A3_Air_F_Orange_Heli_Transport_02 = ['C_IDAP_Heli_Transport_02_F',0.75,'',0];
        _A3_Soft_F_Orange_UGV_01 = ['C_IDAP_UGV_01_F',0.3,'',0];
        _A3_Air_F_Orange_UAV_06 = ['C_IDAP_UAV_06_antimine_F',0.3,'C_IDAP_UAV_06_F',0.15,'C_IDAP_UAV_06_medical_F',0.15,'',0];
        _A3_Structures_F_Heli_Items_Luggage = ['Land_MetalCase_01_large_F',0.05,'Land_MetalCase_01_medium_F',0.05,'Land_PlasticCase_01_large_F',0.05,'Land_PlasticCase_01_medium_F',0.05,'',0];
        _A3_Structures_F_Ind_Cargo = ['Land_CargoBox_V1_F',0.05,'',0];
        _A3_Supplies_F_Heli_CargoNets = ['CargoNet_01_barrels_F',0.05,'CargoNet_01_box_F',0.05,'',0];
        _Sheet2 = _A3_Air_F_Orange_UAV_01+_A3_Structures_F_Orange_Humanitarian_Camps+_A3_Supplies_F_Orange_CargoNets+_A3_Props_F_Orange_Humanitarian_Supplies+_A3_Soft_F_Orange_Truck_02+_A3_Soft_F_Orange_Van_02+_A3_Soft_F_Orange_Offroad_01+_A3_Soft_F_Orange_Offroad_02+_A3_Air_F_Orange_Heli_Transport_02+_A3_Soft_F_Orange_UGV_01+_A3_Air_F_Orange_UAV_06+_A3_Structures_F_Heli_Items_Luggage+_A3_Structures_F_Ind_Cargo+_A3_Supplies_F_Heli_CargoNets+[];

        //import to Arma
        [_zeuslogic,_Sheet2] call bis_fnc_curatorObjectRegisteredTable;
    };
};





